database.clean: false
storm.brokerURL: "tcp://mqtt-broker:1883"
storm.topicList: ["iot-data"]
storm.windowList: [1, 5, 10, 15, 20, 30, 60, 120]

notification.publishMQTT: true
notification.brokerURL: "tcp://mqtt-broker:1883"

notification.house.logGap: 30
notification.house.checkMin: false
notification.house.checkAvg: true
notification.house.checkMax: true

notification.household.logGap: 30
notification.household.checkMin: false
notification.household.checkAvg: true
notification.household.checkMax: true